image: maven:3-jdk-8
deploy:
  image: maven:3.3.9-jdk-8
  script:
    - 'mvn deploy -s ci_settings.xml'
  only:
    - master
build:
  script: "mvn clean package"
  artifacts:
    name: "ItemMods"
    paths: 
    - "target/*.jar"
pages:
  image: "openkbs/jdk-mvn-py3"
  services:
  - 'maven:3-jdk-8'
  before_script:
  - 'pip install mkdocs'
  - 'pip install mkdocs-material'
  script:
  - 'mvn javadoc:javadoc'
  - 'mv target/site/* public'
  - 'mv ./*.md public'
  - 'mkdocs build'
  
  only:
    - master
  artifacts:
    paths:
        - public